### ISSUE TITLE
No Modules in iOS 15

### ISSUE THREAD

**Issue by namcigam** [adafruit/Bluefruit_LE_Connect_v2#45]
I have the iPhone 13 ProMax and the app does not seem to want to work, I have removed and reinstalled it.  I also have an iPhone 8 on 14.7 and it has no issues with the app... 

![IMG_0105](https://user-images.githubusercontent.com/18330397/139469560-061ecfed-1ba6-4cd0-9864-c70db40eecca.PNG)

**Comment by antonio-openroad** [comment]
I have tested it and I didn't find any problems with iOS 15.1

Can you explain in more detail what the problem is? I guess that that the connection fails on your iPhone13

I see that you are tying to connect to a CircuitPython device. I think that your problem is that that device is paired to your iPhone8 and that's why it would refuse to connect to your iPhone13.
Try resetting the CircuitPython device. You should also remove the pairing from your phone in Settings->Bluetooth->CircuitPythonDevice->Information->Forget this device

I hope this helps you

**Comment by namcigam** [comment]
It started working a week after I put in the ticket.  I did not make any changes and it was connected as you can see in the screenshots, it just did not have the lower section 



Michael Brewer
***@***.*** | 512-605-8129
